# Generated by Django 5.2.13 on 2026-04-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Dueño de mascota'), ('clinic', 'Veterinario/a')], default='owner', max_length=10),
        ),
    ]
