# Generated by Django 5.2.13 on 2026-04-30 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_remove_clinic_specialties_remove_clinic_vets_and_more'),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaccine',
            options={'ordering': ['-date_applied']},
        ),
        migrations.AddField(
            model_name='vaccine',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccines', to='clinics.clinic'),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='vet_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='vet_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='vet_license',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
