# Generated by Django 5.2.13 on 2026-05-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_vaccine_options_vaccine_clinic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='feeding',
            field=models.CharField(blank=True, choices=[('balanced', 'Balanceada'), ('homemade', 'Casera'), ('mixed', 'Mixta')], max_length=20),
        ),
        migrations.AddField(
            model_name='pet',
            name='habitat',
            field=models.CharField(blank=True, choices=[('apartment', 'Departamento'), ('house', 'Casa con patio'), ('field', 'Campo')], max_length=20),
        ),
        migrations.AddField(
            model_name='pet',
            name='lives_with_animals',
            field=models.BooleanField(default=False),
        ),
    ]
