# Generated by Django 5.2.13 on 2026-06-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pet_feeding_pet_habitat_pet_lives_with_animals'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='vet_clinic_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
