# Generated by Django 5.2.13 on 2026-06-03 21:52

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0011_clinic_slug'),
        ('pets', '0004_vaccine_vet_clinic_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_photos', to='clinics.clinic')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_photos', to='pets.pet')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
