# Generated by Django 5.2.13 on 2026-06-15 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0012_clinic_slug'),
        ('pets', '0006_vaccine_reminder_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalphoto',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='clinicalphoto',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_photos', to='clinics.clinic'),
        ),
        migrations.AlterField(
            model_name='clinicalphoto',
            name='image',
            field=models.ImageField(upload_to='clinical_photos/'),
        ),
    ]
