# Generated by ChatGPT for VetPaw

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0013_clinicalphoto_pdf_database_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('dog', 'Perro'), ('cat', 'Gato'), ('horse', 'Caballo'), ('rabbit', 'Conejo'), ('bird', 'Ave'), ('cow', 'Vaca / Toro'), ('hamster', 'Hamster'), ('reptile', 'Reptil'), ('fish', 'Pez'), ('other', 'Otro')], max_length=20),
        ),
    ]
