# Generated by Django 5.2 for VetPaw

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0014_alter_pet_species_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayCelebration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('age', models.PositiveIntegerField()),
                ('birthday_date', models.DateField()),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('card_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birthday_celebrations', to='pets.pet')),
            ],
            options={
                'ordering': ['-birthday_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='birthdaycelebration',
            constraint=models.UniqueConstraint(fields=('pet', 'year'), name='unique_pet_birthday_celebration_year'),
        ),
    ]
