# Generated by Django 5.2.13 on 2026-05-16 13:15

import cloudinary.models
import lost_pets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('description', models.TextField()),
                ('contact_type', models.CharField(choices=[('phone', 'Celular'), ('home_phone', 'Teléfono de casa'), ('email', 'Email')], max_length=20)),
                ('contact_value', models.CharField(max_length=150)),
                ('report_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(default=lost_pets.models.expiry_default)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
