# Generated by Django 5.2.13 on 2026-05-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostpet',
            name='report_type',
            field=models.CharField(choices=[('found', 'Encontré una mascota'), ('lost', 'Perdí mi mascota')], default='found', max_length=10),
        ),
    ]
