# Generated by Django 5.2.13 on 2026-05-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_pets', '0002_lostpet_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostpet',
            name='locality',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lostpet',
            name='province',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
