# Generated by Django 5.2.13 on 2026-06-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_pets', '0004_lostpet_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostpet',
            name='breed',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='lostpet',
            name='incident_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lostpet',
            name='pet_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='lostpet',
            name='species',
            field=models.CharField(blank=True, choices=[('dog', 'Perro'), ('cat', 'Gato'), ('bird', 'Pájaro'), ('rabbit', 'Conejo'), ('fish', 'Pez'), ('other', 'Otro')], default='', max_length=20),
        ),
    ]
