# Generated by Django 5.2.13 on 2026-04-29 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_clinic_vets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='specialties',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='vets',
        ),
        migrations.AddField(
            model_name='clinic',
            name='owner',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'clinic'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinic',
            name='services',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
