# Generated by Django 5.2.13 on 2026-05-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_remove_clinic_specialties_remove_clinic_vets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
