# Generated by Django 5.2.13 on 2026-05-24 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0005_clinic_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clinic_photos/')),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='clinics.clinic')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]