# Generated by Django 5.2.13 on 2026-05-26 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0006_clinic_slug_clinicphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_days', models.JSONField(default=list)),
                ('day_hours', models.JSONField(default=dict)),
                ('duration_control', models.PositiveSmallIntegerField(default=30)),
                ('duration_vaccine', models.PositiveSmallIntegerField(default=20)),
                ('duration_surgery', models.PositiveSmallIntegerField(default=90)),
                ('duration_other', models.PositiveSmallIntegerField(default=30)),
                ('interval_minutes', models.PositiveSmallIntegerField(choices=[(0, 'Sin intervalo'), (10, '10 min'), (15, '15 min'), (20, '20 min')], default=10)),
                ('cancel_limit_hours', models.PositiveSmallIntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='clinics.clinic')),
            ],
        ),
    ]