# Generated by Django 5.2.13 on 2026-06-03 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0009_clinic_slug'),
        ('pets', '0004_vaccine_vet_clinic_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicPetAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_appointment', models.DateTimeField()),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_accesses', to='clinics.clinic')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_accesses', to='pets.pet')),
            ],
            options={
                'unique_together': {('clinic', 'pet')},
            },
        ),
    ]