# Generated by Django 5.2.13 on 2026-06-03 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0010_clinic_slug_clinicpetaccess'),
    ]

    operations = [
    ]