# Generated by Django 5.2.13 on 2026-06-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0011_clinic_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
