from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0002_businessprofile_accepts_reservations'),
        ('community', '0008_business_notifications_stage7'),
        ('messaging', '0001_initial'),
        ('pets', '0015_birthdaycelebration'),
    ]
    operations = [
        migrations.CreateModel(
            name='BusinessAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Gratis'), ('pro', 'Pro'), ('plus', 'Plus')], default='free', max_length=12)),
                ('status', models.CharField(choices=[('development', 'Acceso completo durante desarrollo'), ('trial', 'Prueba'), ('active', 'Activo'), ('past_due', 'Pago pendiente'), ('cancelled', 'Cancelado')], default='development', max_length=20)),
                ('monetization_enforced', models.BooleanField(default=False)),
                ('full_access_override', models.BooleanField(default=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_access', to='partners.businessprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('product', 'Producto'), ('service', 'Servicio')], max_length=12)),
                ('category', models.CharField(choices=[('grooming', 'Peluquería e higiene'), ('food', 'Alimentos'), ('accessories', 'Accesorios y juguetes'), ('daycare', 'Guardería'), ('boarding', 'Hospedaje'), ('walking', 'Paseos'), ('training', 'Adiestramiento'), ('transport', 'Transporte'), ('pharmacy', 'Farmacia e higiene'), ('photography', 'Fotografía'), ('other', 'Otro')], default='other', max_length=30)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(max_length=3000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='commerce/catalog/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_on_request', models.BooleanField(default=False)),
                ('promotional_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('species', models.JSONField(blank=True, default=list)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('requires_booking', models.BooleanField(default=False)),
                ('home_service', models.BooleanField(default=False)),
                ('delivery', models.BooleanField(default=False)),
                ('pickup', models.BooleanField(default=False)),
                ('stock_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='partners.businessprofile')),
                ('shared_post', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_item', to='community.post')),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(max_length=2500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='commerce/promotions/')),
                ('previous_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('promotional_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('quantity_available', models.PositiveIntegerField(blank=True, null=True)),
                ('locality', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_promotions', to='partners.businessprofile')),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='commerce.catalogitem')),
                ('shared_post', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commerce_promotion', to='community.post')),
            ],
            options={'ordering': ['ends_at', '-created_at']},
        ),
        migrations.CreateModel(
            name='BusinessProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views', to='partners.businessprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewed_business_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1500)),
                ('status', models.CharField(choices=[('new', 'Nueva'), ('replied', 'Respondida'), ('closed', 'Cerrada')], default='new', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='partners.businessprofile')),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='commerce.catalogitem')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_inquiries', to='messaging.message')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='commerce.promotion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='BusinessReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('notes', models.TextField(blank=True, max_length=1200)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('rejected', 'Rechazada'), ('rescheduled', 'Reprogramada'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('business_note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='partners.businessprofile')),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='commerce.catalogitem')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_reservations', to='pets.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['date', 'start_time', '-created_at']},
        ),
        migrations.CreateModel(
            name='BusinessFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='partners.businessprofile')),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='commerce.catalogitem')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='commerce.promotion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(model_name='catalogitem', index=models.Index(fields=['business', 'is_active', '-created_at'], name='commerce_cat_business_idx')),
        migrations.AddIndex(model_name='catalogitem', index=models.Index(fields=['item_type', 'category', 'is_active'], name='commerce_cat_filter_idx')),
        migrations.AddIndex(model_name='promotion', index=models.Index(fields=['business', 'is_active', 'ends_at'], name='commerce_prom_business_idx')),
        migrations.AddIndex(model_name='promotion', index=models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='commerce_prom_dates_idx')),
        migrations.AddIndex(model_name='businessprofileview', index=models.Index(fields=['business', '-created_at'], name='commerce_view_business_idx')),
        migrations.AddIndex(model_name='businessinquiry', index=models.Index(fields=['business', 'status', '-created_at'], name='commerce_inq_business_idx')),
        migrations.AddIndex(model_name='businessreservation', index=models.Index(fields=['business', 'date', 'status'], name='commerce_res_business_idx')),
        migrations.AddIndex(model_name='businessreservation', index=models.Index(fields=['user', '-created_at'], name='commerce_res_user_idx')),
        migrations.AddConstraint(model_name='businessfavorite', constraint=models.UniqueConstraint(condition=models.Q(('business__isnull', False)), fields=('user', 'business'), name='unique_user_business_favorite')),
        migrations.AddConstraint(model_name='businessfavorite', constraint=models.UniqueConstraint(condition=models.Q(('catalog_item__isnull', False)), fields=('user', 'catalog_item'), name='unique_user_catalog_favorite')),
        migrations.AddConstraint(model_name='businessfavorite', constraint=models.UniqueConstraint(condition=models.Q(('promotion__isnull', False)), fields=('user', 'promotion'), name='unique_user_promotion_favorite')),
    ]
