from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_alter_user_role'),
    ]
    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=210, unique=True)),
                ('responsible_name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, max_length=3000)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/logos/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='partners/covers/')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('province', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('show_public_address', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('species', models.JSONField(blank=True, default=list)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_type', models.CharField(choices=[('grooming', 'Peluquería canina o felina'), ('petshop', 'Petshop'), ('food', 'Alimentos y accesorios'), ('daycare', 'Guardería'), ('boarding', 'Hospedaje'), ('walker', 'Paseador'), ('training', 'Adiestramiento'), ('transport', 'Transporte de mascotas'), ('pharmacy', 'Farmacia veterinaria'), ('photography', 'Fotografía de mascotas'), ('funeral', 'Servicios funerarios'), ('other', 'Otro servicio')], max_length=30)),
                ('services', models.JSONField(blank=True, default=list)),
                ('opening_hours', models.JSONField(blank=True, default=dict)),
                ('home_service', models.BooleanField(default=False)),
                ('delivery', models.BooleanField(default=False)),
                ('online_sales', models.BooleanField(default=False)),
                ('appointment_required', models.BooleanField(default=False)),
                ('is_24h', models.BooleanField(default=False)),
                ('payment_methods', models.JSONField(blank=True, default=list)),
                ('price_range', models.CharField(blank=True, max_length=80)),
                ('promotions', models.TextField(blank=True, max_length=1200)),
                ('tax_id', models.CharField(blank=True, max_length=30)),
                ('legal_name', models.CharField(blank=True, max_length=180)),
                ('owner', models.OneToOneField(limit_choices_to={'role': 'business'}, on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='ShelterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=210, unique=True)),
                ('responsible_name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, max_length=3000)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/logos/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='partners/covers/')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('province', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('show_public_address', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('species', models.JSONField(blank=True, default=list)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shelter_type', models.CharField(choices=[('shelter', 'Refugio'), ('association', 'Asociación protectora'), ('rescue', 'Organización de rescate'), ('foster', 'Hogar de tránsito'), ('independent', 'Rescatista independiente'), ('sanctuary', 'Santuario'), ('other', 'Otro')], max_length=30)),
                ('founded_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('work_area', models.CharField(blank=True, max_length=255)),
                ('activities', models.JSONField(blank=True, default=list)),
                ('capacity_status', models.CharField(choices=[('available', 'Puede recibir animales'), ('limited', 'Cupos limitados'), ('full', 'Capacidad completa'), ('emergency', 'Solo casos urgentes')], default='limited', max_length=20)),
                ('capacity_max', models.PositiveIntegerField(blank=True, null=True)),
                ('current_animals', models.PositiveIntegerField(blank=True, null=True)),
                ('accepting_animals', models.BooleanField(default=False)),
                ('adoption_requirements', models.TextField(blank=True, max_length=2500)),
                ('adoption_area', models.CharField(blank=True, max_length=255)),
                ('adoption_interview', models.BooleanField(default=True)),
                ('adoption_follow_up', models.BooleanField(default=True)),
                ('adoption_castration_commitment', models.BooleanField(default=True)),
                ('adoption_safe_home_required', models.BooleanField(default=True)),
                ('adoption_outside_province', models.BooleanField(default=False)),
                ('needs_volunteers', models.BooleanField(default=False)),
                ('needs_foster_homes', models.BooleanField(default=False)),
                ('accepts_donations', models.BooleanField(default=False)),
                ('accepts_food', models.BooleanField(default=False)),
                ('accepts_medicine', models.BooleanField(default=False)),
                ('needs_transport', models.BooleanField(default=False)),
                ('needs_vet_help', models.BooleanField(default=False)),
                ('needs_sharing', models.BooleanField(default=True)),
                ('donation_alias', models.CharField(blank=True, max_length=120)),
                ('donation_cbu', models.CharField(blank=True, max_length=80)),
                ('donation_needs', models.TextField(blank=True, max_length=1800)),
                ('legal_status', models.CharField(blank=True, max_length=180)),
                ('tax_id', models.CharField(blank=True, max_length=30)),
                ('registration_number', models.CharField(blank=True, max_length=120)),
                ('owner', models.OneToOneField(limit_choices_to={'role': 'shelter'}, on_delete=django.db.models.deletion.CASCADE, related_name='shelter_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['name']},
        ),
        migrations.AddIndex(model_name='businessprofile', index=models.Index(fields=['business_type', 'is_active'], name='partners_bu_busines_2b5025_idx')),
        migrations.AddIndex(model_name='businessprofile', index=models.Index(fields=['province', 'locality'], name='partners_bu_provinc_9120df_idx')),
        migrations.AddIndex(model_name='shelterprofile', index=models.Index(fields=['shelter_type', 'is_active'], name='partners_sh_shelter_cdc8c3_idx')),
        migrations.AddIndex(model_name='shelterprofile', index=models.Index(fields=['province', 'locality'], name='partners_sh_provinc_8f31b5_idx')),
        migrations.AddIndex(model_name='shelterprofile', index=models.Index(fields=['capacity_status', 'accepting_animals'], name='partners_sh_capacit_f09b4e_idx')),
    ]
