# Generated by Django 5.2.13 on 2026-04-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='seen_by_owner',
            field=models.BooleanField(default=True),
        ),
    ]
