# Generated by Django 5.2.13 on 2026-04-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_seen_by_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado'), ('done', 'Realizado'), ('no_show', 'Ausente')], default='pending', max_length=15),
        ),
    ]
