# Generated by Django 5.2.13 on 2026-04-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='vet',
        ),
        migrations.AddField(
            model_name='visit',
            name='vet_first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='vet_last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='vet_license',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
