# Generated by Django 5.2.13 on 2026-05-26 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointment_reminder_sent'),
        ('pets', '0003_pet_feeding_pet_habitat_pet_lives_with_animals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('control', 'Control general'), ('vaccine', 'Vacunación'), ('surgery', 'Cirugía'), ('other', 'Otro')], default='control', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='external_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='pets.pet'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado'), ('completed', 'Realizado'), ('no_show', 'Ausente')], default='confirmed', max_length=15),
        ),
    ]
