# Generated by Django 5.2.13 on 2026-06-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_appointment_appointment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consent_shown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='vet_clinic_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
