# Generated by Django 5.2.13 on 2026-06-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_appointment_consent_shown_visit_vet_clinic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='seen_by_clinic',
            field=models.BooleanField(default=True),
        ),
    ]
